version: "3.1"
services:
  mysql:
    image: mysql:5.7
    container_name: container-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3305:3306
    volumes:
      - ./database:/var/lib/mysql