version: '3'

services: 
  # app:
  #   image: node
  #   container_name: associations
  #   tty: true
  #   stdin_open: true
  #   command: bash
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-proot"]
      timeout: 10s
      retries: 10
      start_period: 10s