version: '3.1'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3305:3306
    container_name: compose-dockerSQL
    volumes:
        - ./database:/var/lib/mysql