version: '3'

services: 
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-proot"]
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql

  api:
    build: .
    environment:
      - APP_PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3000:3000